### ISSUE TITLE
goreleaser-action downloads i386 version of installer on arm64

### ISSUE THREAD

**Issue by tenyo** [crazy-max/ghaction-goreleaser#297]
I'm trying to use goreleaser on an arm64 self-hosted runner (Raspberry Pi 4) but it's downloading the i386 version (which subsequently fails to execute):

```
Run goreleaser/goreleaser-action@v2
  with:
    distribution: goreleaser
    version: v0.175.0
    args: release --rm-dist
    workdir: .
    install-only: false
  env:
    GOROOT: /tmp/actions-runner/_work/_tool/go/1.16.7/arm64
    GITHUB_TOKEN: ***
Downloading https://github.com/goreleaser/goreleaser/releases/download/v0.175.0/goreleaser_Linux_i386.tar.gz
Extracting GoReleaser
```

From my runner:
```
$ uname -m
aarch64
```

From my `release.yml`:
```
jobs:
  goreleaser:
    runs-on: ARM64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: v0.175.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
